name: Entcraft Points
main: net.entcraft.entpoints.Main
description: Handles Ent Points for the Entcraft server
author: AlexDGr8r
version: 1.0

commands:
  points:
    description: Base points command
    usage: /points <args>
  rewards:
    description: Base Reward System command
    usage: /rewards <args>